const category = [
  {
    name: "패션의류/잡화",
    subs: [
      {
        name: "여성패션",
        subs: [
          { name: "의류" },
          { name: "속옷/잠옷" },
          { name: "신발" },
          { name: "가방/잡화" },
        ],
      },
      {
        name: "남성패션",
        subs: [
          { name: "의류" },
          { name: "속옷/잠옷" },
          { name: "신발" },
          { name: "가방/잡화" },
        ],
      },
      {
        name: "남녀 공용 의류",
        subs: [
          { name: "티셔츠" },
          { name: "맨투맨/후드티" },
          { name: "셔츠" },
          { name: "바지" },
          { name: "트레이닝복" },
          { name: "후드집업/집업류" },
          { name: "니트류/조끼" },
          { name: "아우터" },
          { name: "테마의류" },
          { name: "커플룩/패밀리룩" },
        ],
      },
      {
        name: "유아동패션",
        subs: [{ name: "베이비" }, { name: "여아" }, { name: "남아" }],
      },
    ],
  },
  {
    name: "뷰티",
    subs: [
      { name: "명품뷰티", subs: [] },
      {
        name: "스킨케어",
        subs: [
          { name: "스킨" },
          { name: "로션" },
          { name: "에센스/세럼/앰플" },
          { name: "미스트" },
          { name: "오일" },
          { name: "크림/올인원" },
          { name: "기초세트" },
          { name: "마스크/팩" },
          { name: "선케어/태닝" },
        ],
      },
      { name: "클렌징/필링", subs: [] },
      { name: "더마코스메틱", subs: [] },
      { name: "메이크업", subs: [] },
      { name: "향수", subs: [] },
      { name: "남성화장품", subs: [] },
      { name: "네일", subs: [] },
      { name: "뷰티소품", subs: [] },
      { name: "어린이화장품", subs: [] },
      { name: "로드샵", subs: [] },
      { name: "헤어", subs: [] },
      { name: "바디", subs: [] },
      { name: "선물세트/키트", subs: [] },
    ],
  },
  {
    name: "출산/유아동",
    subs: [
      { name: "베이비패션", subs: [] },
      { name: "여아키즈패션", subs: [] },
      { name: "남아키즈패션", subs: [] },
      { name: "기저귀", subs: [] },
      { name: "물티슈", subs: [] },
      { name: "분유/어린이식품", subs: [] },
      { name: "수유용품", subs: [] },
      { name: "이유용품/유아식기", subs: [] },
      { name: "유모차/웨건", subs: [] },
      { name: "카시트", subs: [] },
      { name: "아기띠/외출용품", subs: [] },
      { name: "유아동침구", subs: [] },
      { name: "매트/안전용품", subs: [] },
      { name: "유아가구/인테리어", subs: [] },
      { name: "욕실용품/스킨케어", subs: [] },
      { name: "위생/건강/세제", subs: [] },
    ],
  },
  {
    name: "식품",
    subs: [
      { name: "유기농/친환경 전문관", subs: [] },
      { name: "과일", subs: [] },
      { name: "견과/건과", subs: [] },
      { name: "채소", subs: [] },
      { name: "쌀/잡곡", subs: [] },
      { name: "축산/계란", subs: [] },
      { name: "수산물/건어물", subs: [] },
      { name: "생수/음료", subs: [] },
      { name: "커피/원두/차", subs: [] },
      { name: "과자/초콜릿/시리얼", subs: [] },
      { name: "면/통조림/가공식품", subs: [] },
      { name: "가루/조미료/오일", subs: [] },
      { name: "장/소스/드레싱/식초", subs: [] },
      { name: "유제품/아이스크림", subs: [] },
      { name: "냉장/냉동/간편요리", subs: [] },
      { name: "건강식품", subs: [] },
    ],
  },
  {
    name: "주방용품",
    subs: [
      { name: "주방가전", sub: [] },
      { name: "냄비/프라이팬", sub: [] },
      { name: "칼/도마", sub: [] },
      { name: "주방조리도구", sub: [] },
      { name: "그릇/홈세트", sub: [] },
      { name: "수저/커트러리", sub: [] },
      { name: "컵/잔/텀블러", sub: [] },
      { name: "커피/티/와인", sub: [] },
      { name: "주방수납/정리", sub: [] },
      { name: "밀폐저장/도시락", sub: [] },
      { name: "주방잡화", sub: [] },
      { name: "일회용품/종이컵", sub: [] },
      { name: "보온/보냉용품", sub: [] },
      { name: "이유/유아식기", sub: [] },
      { name: "베이킹용품", sub: [] },
      { name: "교자상/제수용품", sub: [] },
    ],
  },
  {
    name: "생활용품",
    subs: [
      { name: "헤어/바디/세안", sub: [] },
      { name: "구강/면도", sub: [] },
      { name: "화장지/물티슈", sub: [] },
      { name: "생리대/성인기저귀", sub: [] },
      { name: "기저귀", sub: [] },
      { name: "세탁세제", sub: [] },
      { name: "청소/주방세제", sub: [] },
      { name: "탈취/방향/살충", sub: [] },
      { name: "건강/의료용품", sub: [] },
      { name: "성인용품(19)", sub: [] },
      { name: "세탁/청소용품", sub: [] },
      { name: "욕실용품", sub: [] },
      { name: "생활전기용품", sub: [] },
      { name: "수납/정리", sub: [] },
      { name: "주방수납/잡화", sub: [] },
      { name: "생활잡화", sub: [] },
    ],
  },
  {
    name: "홈인테리어",
    subs: [
      { name: "봄침구샵", sub: [] },
      { name: "싱글하우스", sub: [] },
      { name: "홈데코", sub: [] },
      { name: "가구", sub: [] },
      { name: "수납/정리", sub: [] },
      { name: "침구", sub: [] },
      { name: "커튼/블라인드", sub: [] },
      { name: "카페트/쿠션/거실화", sub: [] },
      { name: "수예/수선", sub: [] },
      { name: "욕실용품", sub: [] },
      { name: "조명/스탠드", sub: [] },
      { name: "셀프인테리어", sub: [] },
      { name: "원예/가드닝", sub: [] },
    ],
  },
  {
    name: "가전디지털",
    subs: [
      { name: "TV/영상가전", sub: [] },
      { name: "냉장고", sub: [] },
      { name: "세탁기/건조기", sub: [] },
      { name: "생활가전", sub: [] },
      { name: "청소기", sub: [] },
      { name: "계절가전", sub: [] },
      { name: "이미용가전", sub: [] },
      { name: "건강가전", sub: [] },
      { name: "주방가전", sub: [] },
      { name: "노트북", sub: [] },
      { name: "데스크탑", sub: [] },
      { name: "모니터", sub: [] },
      { name: "키보드/마우스", sub: [] },
      { name: "저장장치", sub: [] },
      { name: "프린터/복합기", sub: [] },
      { name: "PC부품", sub: [] },
    ],
  },
  {
    name: "스포츠/레저",
    subs: [
      { name: "캠핑전문관", sub: [] },
      { name: "홈트레이닝", sub: [] },
      { name: "수영/수상스포츠", sub: [] },
      { name: "골프", sub: [] },
      { name: "자전거", sub: [] },
      { name: "킥보드/스케이트", sub: [] },
      { name: "낚시", sub: [] },
      { name: "등산/아웃도어", sub: [] },
      { name: "스포츠신발", sub: [] },
      { name: "남성스포츠의류", sub: [] },
      { name: "여성스포츠의류", sub: [] },
      { name: "유아스포츠의류", sub: [] },
      { name: "스포츠잡화", sub: [] },
      { name: "구기스포츠", sub: [] },
      { name: "라켓스포츠", sub: [] },
      { name: "헬스/요가/댄스", sub: [] },
    ],
  },
  {
    name: "자동차용품",
    subs: [
      { name: "인테리어", sub: [] },
      { name: "익스테리어", sub: [] },
      { name: "세차/카케어", sub: [] },
      { name: "차량용 전자기기", sub: [] },
      { name: "차량관리/소모품", sub: [] },
      { name: "RV/아웃도어", sub: [] },
      { name: "부품/안전/공구", sub: [] },
      { name: "오토바이/전동킥보드", sub: [] },
      { name: "로켓설치 타이어", sub: [] },
    ],
  },
  {
    name: "도서/음반/DVD",
    subs: [
      { name: "유아/어린이", sub: [] },
      { name: "소설/에세이/시", sub: [] },
      { name: "초중고참고서", sub: [] },
      { name: "초등학생", sub: [] },
      { name: "중학생", sub: [] },
      { name: "고등학생", sub: [] },
      { name: "가정 살림", sub: [] },
      { name: "건강 취미", sub: [] },
      { name: "경제 경영", sub: [] },
      { name: "과학/공학", sub: [] },
      { name: "국어/외국어/사전", sub: [] },
      { name: "대학교재", sub: [] },
      { name: "만화/라이트노벨", sub: [] },
      { name: "사회 정치", sub: [] },
      { name: "수험서/자격증", sub: [] },
      { name: "여행", sub: [] },
      { name: "역사", sub: [] },
      { name: "예술", sub: [] },
      { name: "인문", sub: [] },
    ],
  },
  {
    name: "완구/취미",
    subs: [
      { name: "캐릭터별완구", sub: [] },
      { name: "신생아/영아완구", sub: [] },
      { name: "로봇/작동완구", sub: [] },
      { name: "역할놀이", sub: [] },
      { name: "블록놀이", sub: [] },
      { name: "인형", sub: [] },
      { name: "물놀이/계절완구", sub: [] },
      { name: "승용완구", sub: [] },
      { name: "스포츠/야외완구", sub: [] },
      { name: "실내대형완구", sub: [] },
      { name: "STEAM완구", sub: [] },
      { name: "학습완구/교구", sub: [] },
      { name: "보드게임", sub: [] },
      { name: "RC완구/부품", sub: [] },
      { name: "퍼즐/큐브/피젯토이", sub: [] },
      { name: "프라모델", sub: [] },
    ],
  },
  {
    name: "문구/오피스",
    subs: [
      { name: "사무용품 전문관", sub: [] },
      { name: "미술/화방용품", sub: [] },
      { name: "캐릭터 문구", sub: [] },
      { name: "학용품/수업준비", sub: [] },
      { name: "필기류", sub: [] },
      { name: "노트/메모지", sub: [] },
      { name: "다이어리/플래너", sub: [] },
      { name: "바인더/파일", sub: [] },
      { name: "파티/이벤트", sub: [] },
      { name: "데코/포장용품", sub: [] },
      { name: "카드/엽서/봉투", sub: [] },
      { name: "앨범", sub: [] },
      { name: "복사용품/라벨지", sub: [] },
      { name: "보드/칠판/광고", sub: [] },
    ],
  },
  {
    name: "반려동물용품",
    subs: [
      { name: "강아지 사료", sub: [] },
      { name: "강아지 간식", sub: [] },
      { name: "강아지 영양제", sub: [] },
      { name: "강아지 용품", sub: [] },
      { name: "고양이 사료", sub: [] },
      { name: "고양이 간식", sub: [] },
      { name: "고양이 영양제", sub: [] },
      { name: "고양이 용품", sub: [] },
      { name: "펫프리미엄", sub: [] },
      { name: "펫티켓 산책용품", sub: [] },
      { name: "관상어 용품", sub: [] },
      { name: "소동물/가축용품", sub: [] },
    ],
  },
  {
    name: "헬스/건강식품",
    subs: [
      { name: "건강기능식품", sub: [] },
      { name: "성인용 건강식품", sub: [] },
      { name: "여성용 건강식품", sub: [] },
      { name: "남성용 건강식품", sub: [] },
      { name: "임산부 건강식품", sub: [] },
      { name: "시니어 건강식품", sub: [] },
      { name: "어린이 건강식품", sub: [] },
      { name: "비타민/미네랄", sub: [] },
      { name: "영양제", sub: [] },
      { name: "허브/식물추출물", sub: [] },
      { name: "홍삼/인삼", sub: [] },
      { name: "건강즙/음료", sub: [] },
      { name: "꿀/프로폴리스", sub: [] },
      { name: "건강분말/건강환", sub: [] },
      { name: "헬스보충식품", sub: [] },
      { name: "다이어트/이너뷰티", sub: [] },
    ],
  },
];

module.exports = category;
